import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
TERMINAL = "alacritty"

[font]
size = 10.0

[font.normal]
#family = "Hack Nerd Font"
family = "Hurmit Nerd Font"
#style = "Regular"

[scrolling]
history = 100000

[window]
dynamic_title = true
opacity = 1.0
title = "Terminal"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 3
y = 3
